spring:
  application:
    name: ecloset-backend
    
  datasource:
    url: jdbc:postgresql://localhost:5432/ecloset
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: ${JWT_SECRET:mySuperSecretKeyForLocalDevOnly4752!}
    access-expiration-ms: 3600000      # 60 минут
    refresh-expiration-ms: 2592000000  # 30 дней

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG